### ISSUE TITLE
Date prop not optional

### ISSUE THREAD

**Issue by naodya** [aboveyunhai/chakra-dayzed-datepicker#2]
The `date` prop always expect a `Date`, ideally it should work if date is not supplied.

**Comment by aboveyunhai** [comment]
> The `date` prop always expect a `Date`, ideally it should work if date is not supplied.

You can simply provide your own default `date={ date || new Date()}`

If you just want it to work without `useState` hook, it means I will have to encapsulate the `date` state for you. Then it will be difficult for user to use the date state outside out component. For example, use it inside `Formik`. 
Actually, that's the primary reason why I create the lib at that moment.

I'm actually rolling out the date range picker due to the project need. So idk something might change.
