### ISSUE TITLE
How to automatically close Popover after select endDate on RangeDatepicker

### ISSUE THREAD

**Issue by biko8** [aboveyunhai/chakra-dayzed-datepicker#25]
In advance, thanks for the component! Its awesome! 👍 

There is some method to close automatically the Popover when user selects the endDate on RangeDatepicker?

**Comment by aboveyunhai** [comment]
I don't think so. 
I personally have weird feeling about the user-prefer behavior. It seems like some prefer to have a confirm button inside the panel, some prefer the button to be outside, and also the auto close like you mentioned. 
That's why I want to do #16 so you can write your own input wrapper, meanwhile we can still create our own wrapper for simple usage.

**Comment by biko8** [comment]
Its true. I understand you. But I think is a good idea to have all the possibilities.
Its very good idea to allow developers to write their own input wrapper.
And also can be a good idea to have new config like "closeOnSelect: boolean". (This seems much easy to implement, and allows developers to have it implemented quickly, without rewrite nothing."

But I'm agree with you, that if developers implement their own input wrapper, can implement that.

Thanks for the work in these components! 👍

**Comment by aboveyunhai** [comment]
pretty fair. Let me find a time to add that feature.

**Comment by aboveyunhai** [comment]
close by #35
